package vu.lt.mybatis.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @return the value of PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @param description the value for PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}