package vu.lt.mybatis.model;

import java.util.Date;

public class Session {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SESSION.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SESSION.SESSION_TIME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Date sessionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SESSION.TICKET_PRICE
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Double ticketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SESSION.TICKETS_TOTAL
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Integer ticketsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SESSION.MOVIE_ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Integer movieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SESSION.ID
     *
     * @return the value of PUBLIC.SESSION.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SESSION.ID
     *
     * @param id the value for PUBLIC.SESSION.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SESSION.SESSION_TIME
     *
     * @return the value of PUBLIC.SESSION.SESSION_TIME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Date getSessionTime() {
        return sessionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SESSION.SESSION_TIME
     *
     * @param sessionTime the value for PUBLIC.SESSION.SESSION_TIME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setSessionTime(Date sessionTime) {
        this.sessionTime = sessionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SESSION.TICKET_PRICE
     *
     * @return the value of PUBLIC.SESSION.TICKET_PRICE
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Double getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SESSION.TICKET_PRICE
     *
     * @param ticketPrice the value for PUBLIC.SESSION.TICKET_PRICE
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SESSION.TICKETS_TOTAL
     *
     * @return the value of PUBLIC.SESSION.TICKETS_TOTAL
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Integer getTicketsTotal() {
        return ticketsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SESSION.TICKETS_TOTAL
     *
     * @param ticketsTotal the value for PUBLIC.SESSION.TICKETS_TOTAL
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setTicketsTotal(Integer ticketsTotal) {
        this.ticketsTotal = ticketsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SESSION.MOVIE_ID
     *
     * @return the value of PUBLIC.SESSION.MOVIE_ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SESSION.MOVIE_ID
     *
     * @param movieId the value for PUBLIC.SESSION.MOVIE_ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }
}