package vu.lt.mybatis.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.SURNAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.NAME
     *
     * @return the value of PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.NAME
     *
     * @param name the value for PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.SURNAME
     *
     * @return the value of PUBLIC.USER.SURNAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.SURNAME
     *
     * @param surname the value for PUBLIC.USER.SURNAME
     *
     * @mbg.generated Tue May 05 13:09:24 EEST 2020
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}